import { GENERATED_ATTRIBUTE, SKIPPED_ROLES, SKIPPED_TAGS } from "./constants";
import { splitText } from "./processor";
import type { AnchorOptions } from "./types";

/**
 * Applies visual anchors to text nodes below an element. Generated `<b>` tags
 * are purely presentational; unlike `<strong>`, they do not add emphasis for
 * assistive technology.
 */
export function processElement(element: HTMLElement, options: AnchorOptions = {}): void {
  const document = element.ownerDocument;
  const nodeFilter = document.defaultView?.NodeFilter ?? NodeFilter;
  const walker = document.createTreeWalker(element, nodeFilter.SHOW_TEXT, {
    acceptNode(node) {
      return shouldProcessTextNode(node)
        ? nodeFilter.FILTER_ACCEPT
        : nodeFilter.FILTER_REJECT;
    }
  });

  // Gather first: replacing a text node while a TreeWalker is positioned on it
  // can otherwise cause browser-specific traversal behaviour.
  const textNodes: Text[] = [];
  while (walker.nextNode()) textNodes.push(walker.currentNode as Text);

  for (const textNode of textNodes) replaceTextNode(textNode, options);
}

/** Removes only markup generated by this package, restoring original text. */
export function restoreElement(element: HTMLElement): void {
  const generated = Array.from(
    element.querySelectorAll<HTMLElement>(`[${GENERATED_ATTRIBUTE}="text"]`)
  );
  for (const node of generated) node.replaceWith(node.ownerDocument.createTextNode(node.textContent ?? ""));
  element.normalize();
}

function shouldProcessTextNode(node: Node): node is Text {
  if (node.nodeType !== node.TEXT_NODE || !node.nodeValue?.trim()) return false;
  const parent = node.parentElement;
  if (!parent) return false;

  for (let current: Element | null = parent; current; current = current.parentElement) {
    const role = current.getAttribute("role");
    if (
      SKIPPED_TAGS.has(current.tagName)
      || current.hasAttribute(GENERATED_ATTRIBUTE)
      || (current as HTMLElement).isContentEditable === true
      || (role !== null && SKIPPED_ROLES.has(role))
      || current.hasAttribute("aria-live")
      || current.getAttribute("aria-hidden") === "true"
    ) return false;
  }
  return true;
}

function replaceTextNode(textNode: Text, options: AnchorOptions): void {
  const segments = splitText(textNode.data, options);
  if (!segments.some((segment) => segment.bold)) return;

  // Wrapping the complete original text node makes processing durable and
  // idempotent. It also permits newly appended sibling text to be processed
  // later by the extension's MutationObserver.
  const wrapper = textNode.ownerDocument.createElement("span");
  wrapper.setAttribute(GENERATED_ATTRIBUTE, "text");
  // Keep every original text node as one inline unit. `display: contents`
  // promotes the bold prefix and remaining text to separate flex/grid items,
  // which makes text in layout-heavy links appear as "Sta rted".
  wrapper.style.display = "inline";

  for (const segment of segments) {
    if (!segment.bold) {
      wrapper.append(textNode.ownerDocument.createTextNode(segment.value));
      continue;
    }

    const bold = textNode.ownerDocument.createElement("b");
    bold.setAttribute(GENERATED_ATTRIBUTE, "fixation");
    bold.className = "clamly-anchor-bold";
    bold.textContent = segment.value;
    wrapper.append(bold);
  }
  textNode.replaceWith(wrapper);
}
